#!/bin/bash
# =============================================================================
# MVP (MPV-Based) Signage Device — Automated Raspberry Pi Setup
# =============================================================================
# Usage:
#   ./setup-mvp.sh [options]
#
# Options:
#   -d, --device-id ID       Device ID (default: 3)
#   -n, --name NAME          Device name (default: MVP-Player-3)
#   -l, --location LOC       Device location (default: Main Hall)
#   -s, --server URL         Server URL (default: http://192.168.1.100:5000/api)
#   -p, --serial-port PORT   Arduino serial port (default: /dev/ttyUSB0)
#   -f, --folder NAME        Per-device folder name (default: Device3)
#   -h, --help               Show this help message
#
# Example:
#   ./setup-mvp.sh -d 3 -n "Hall-Screen" -l "Conference Hall" -s "http://192.168.1.50:5000/api"
# =============================================================================

set -e

# ── Defaults ──
DEVICE_ID="3"
DEVICE_NAME="MVP-Player-3"
LOCATION="Main Hall"
SERVER_URL="http://192.168.1.100:5000/api"
SERIAL_PORT="/dev/ttyUSB0"
FOLDER_NAME="Device3"

# ── Parse arguments ──
while [[ $# -gt 0 ]]; do
    case "$1" in
        -d|--device-id) DEVICE_ID="$2"; shift 2 ;;
        -n|--name) DEVICE_NAME="$2"; shift 2 ;;
        -l|--location) LOCATION="$2"; shift 2 ;;
        -s|--server) SERVER_URL="$2"; shift 2 ;;
        -p|--serial-port) SERIAL_PORT="$2"; shift 2 ;;
        -f|--folder) FOLDER_NAME="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,18p' "$0"
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MVP_TEMPLATE="$SCRIPT_DIR/mvpDevice"
DEVICE_DIR="$HOME/signage/$FOLDER_NAME"

echo "========================================"
echo "  MVP (MPV) Device Setup"
echo "========================================"
echo ""
echo "Device ID:      $DEVICE_ID"
echo "Device Name:    $DEVICE_NAME"
echo "Location:       $LOCATION"
echo "Server URL:     $SERVER_URL"
echo "Serial Port:    $SERIAL_PORT"
echo "Folder:         $FOLDER_NAME"
echo ""

# ── Confirm (if interactive) ──
if [[ -t 0 ]]; then
    read -p "Continue? [Y/n]: " confirm
    if [[ "$confirm" =~ ^[Nn]$ ]]; then
        echo "Aborted."
        exit 0
    fi
fi

# ── 1. System Update ──
echo ""
echo "[1/6] Updating system..."
sudo apt update && sudo apt full-upgrade -y
sudo apt install -y git curl wget vim

# ── 2. Install MPV and Python Dependencies ──
echo ""
echo "[2/6] Installing MPV and Python dependencies..."
sudo apt install -y \
    mpv \
    python3-requests \
    python3-socketio \
    python3-serial \
    python3-setuptools

# Verify MPV
if ! command -v mpv &> /dev/null; then
    echo "ERROR: MPV installation failed."
    exit 1
fi
echo "MPV version: $(mpv --version | head -1)"

# ── 3. Arduino Serial Permissions ──
echo ""
echo "[3/6] Setting up Arduino serial permissions..."
sudo usermod -aG dialout "$USER"
echo "Added '$USER' to 'dialout' group."

# ── 4. Optional: Brightness Control ──
# NOTE: MVP handles brightness internally via a daemon thread.
# We only install brightnessctl here; no separate service is needed.
echo ""
read -p "[4/6] Install brightnessctl for auto-brightness? [y/N]: " brightness_answer
if [[ "$brightness_answer" =~ ^[Yy]$ ]]; then
    sudo apt install -y brightnessctl
    echo "brightnessctl installed."
else
    echo "Skipped brightnessctl."
fi

# ── 5. Deploy Agent Code ──
echo ""
echo "[5/6] Deploying agent code..."

mkdir -p "$HOME/signage"

# Copy template to device folder
cp -r "$MVP_TEMPLATE" "$DEVICE_DIR"
mkdir -p "$DEVICE_DIR/downloads"
mkdir -p "$DEVICE_DIR/data"

echo "Copied mvpDevice template to $DEVICE_DIR"

# Create config.py
cat > "$DEVICE_DIR/config.py" <<EOF
import os

# Device config — generated by setup-mvp.sh on $(date -Iseconds)

SERVER_URL = "$SERVER_URL"
DEVICE_NAME = "$DEVICE_NAME"
LOCATION = "$LOCATION"
DEVICE_ID = $DEVICE_ID

# Server-assigned token (populated automatically after first Socket.IO heartbeat).
# Keep this secret — do not commit production values.
DEVICE_TOKEN = ""

# Local player HTTP server (the browser connects here)
PLAYER_HOST = "0.0.0.0"
PLAYER_PORT = 8080

# Content cache directory (relative to this script)
CACHE_DIR = "downloads"

# Arduino Serial Configuration
SERIAL_PORT = "$SERIAL_PORT"
BAUD_RATE = 9600
RAIN_THRESHOLD = 500

# How often to poll the server for deployments (seconds)
SYNC_INTERVAL = 60

# Default duration for live streams if not specified (seconds)
LIVE_STREAM_DURATION = 3600

# Local emergency fallback asset path (relative to this script's directory)
EMERGENCY_FALLBACK = os.path.join(os.path.dirname(__file__), "emergency_fallback.mp4")

# Disconnection timeout: if no server contact for this many hours, purge content
# and display the disconnection image
DISCONNECTION_TIMEOUT_HOURS = 72
DISCONNECTION_IMAGE = os.path.join(os.path.dirname(__file__), "disconnection.png")

# Default image shown when the device has no scheduled content
NO_CONTENT_IMAGE = os.path.join(os.path.dirname(__file__), "no_content.jpg")
EOF

echo "Created $DEVICE_DIR/config.py"

# Ensure fallback assets exist
for asset in emergency_fallback.mp4 disconnection.png no_content.jpg; do
    if [[ ! -f "$DEVICE_DIR/$asset" ]]; then
        echo "WARNING: $asset not found in template."
    fi
done

echo ""
echo "Agent deployed to: $DEVICE_DIR"

# ── 6. Create systemd Service ──
echo ""
echo "[6/6] Creating systemd service..."

SERVICE_NAME="mvp-player-${FOLDER_NAME,,}.service"
SERVICE_FILE="/etc/systemd/system/$SERVICE_NAME"

sudo tee "$SERVICE_FILE" > /dev/null <<EOF
[Unit]
Description=MVP Player ($DEVICE_NAME)
After=network.target
Wants=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$DEVICE_DIR
Environment=PYTHONUNBUFFERED=1
ExecStart=/usr/bin/python3 $DEVICE_DIR/mvp-player.py
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"

echo "Created $SERVICE_FILE"
echo "Service name: $SERVICE_NAME"

# NOTE: MVP does NOT need a separate brightness-control service.
# mvp-player.py already runs brightness_control.run() as an internal
# daemon thread. A separate systemd service would create a conflicting
# second brightness loop.

# ── Summary ──
echo ""
echo "========================================"
echo "  Setup Complete!"
echo "========================================"
echo ""
echo "Device folder:     $DEVICE_DIR"
echo "Systemd service:   $SERVICE_NAME"
echo ""
echo "Next steps:"
echo "  1. Reboot or log out and back in for 'dialout' group to take effect."
echo "  2. Start the agent manually to test:"
echo "       cd $DEVICE_DIR && python3 mvp-player.py"
echo "  3. If testing succeeds, start the service:"
echo "       sudo systemctl start $SERVICE_NAME"
echo "  4. Approve the device in the web UI and note the DEVICE_ID."
echo "  5. Update config.py if the assigned DEVICE_ID differs."
echo ""
echo "View logs:"
echo "       sudo journalctl -u $SERVICE_NAME -f"
echo ""
